export const INIT_POSTS = "INIT_POSTS";
export const INIT_POSTS_SAGA = "INIT_POSTS_SAGA";
export const INIT_POSTS_SUCCSSS = "INIT_POSTS_SUCCSSS";
export const INIT_POSTS_FAIL = "INIT_POSTS_FAIL";

export const START_AUTH = "START_AUTH";
export const START_AUTH_SAGA = "START_AUTH_SAGA";
export const START_AUTH_SUCCESS = "START_AUTH_SUCCESS";
export const START_AUTH_FAIL = "START_AUTH_FAIL";
export const PERSONAL_DATA_AUTH = "PERSONAL_DATA_AUTH";
export const PERSONAL_DATA_AUTH_SAGA = "PERSONAL_DATA_AUTH_SAGA";
export const CONFIRM_FIRST_LOGIN = "CONFIRM_FIRST_LOGIN";
export const INIT_LOGOUT = "INIT_LOGOUT";
export const LOGOUT = "LOGOUT";
export const INIT_LOGOUT_SAGA = "INIT_LOGOUT_SAGA";
export const CHECK_TIMEOUT = "CHECK_TIMEOUT";
export const AUTO_LOGIN = "AUTO_LOGIN";

export const FETCH_PERSONAL_DATA = "FETCH_PERSONAL_DATA";
export const FETCH_PERSONAL_DATA_SUCCESS = "FETCH_PERSONAL_DATA_SUCCESS";
export const FETCH_PERSONAL_DATA_FAIL = "FETCH_PERSONAL_DATA_FAIL";
export const CLEAR_PERSONAL_DATA = "CLEAR_PERSONAL_DATA";

export const START_NEWPOST = "START_NEWPOST";
export const POST_NEWPOST_SUCCESS = "POST_NEWPOST_SUCCESS";
export const POST_NEWPOST_FAIL = "POST_NEWPOST_FAIL";
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
export const FETCH_MYPOSTS = "FETCH_MYPOSTS";
export const FETCH_MYPOSTS_SUCCESS = "FETCH_MYPOSTS_SUCCESS";
export const FETCH_MYPOSTS_FAIL = "FETCH_MYPOSTS_FAIL";
